name: Neura E2E Automation

on:
  schedule:               # ── automatic run every hour (UTC)
    - cron: '0 * * * *'
  push:                    # ── CI for main branch
    branches: [ main ]
  pull_request:            # ── CI for all PRs
    branches: [ '**' ]
  workflow_dispatch:       # ── manual trigger in the GitHub UI
    inputs:
      spec_file:
        description: 'Run only this spec file (e.g. tests/bridge-flows.spec.js)'
        required: false
        default: ''
      test_pattern:
        description: 'Playwright --grep pattern (optional)'
        required: false
        default: ''

jobs:
  e2e:
    name: Playwright tests
    runs-on: ubuntu-latest
    timeout-minutes: 30

    # cancel the previous hourly run if a new one starts
    concurrency:
      group: e2e-${{ github.ref }}-${{ github.event_name == 'schedule' && 'hourly' || 'ci' }}
      cancel-in-progress: true

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm

      - name: Install dependencies
        run: |
          npm ci
          npx playwright install --with-deps

      # ──────────────────────────────── run tests ────────────────────────────────
      - name: Run Playwright tests
        run: |
          if [[ -n "${{ github.event.inputs.spec_file }}" ]]; then
            echo "🎯 Running single spec: ${{ github.event.inputs.spec_file }}"
            npx playwright test "${{ github.event.inputs.spec_file }}"
          elif [[ -n "${{ github.event.inputs.test_pattern }}" ]]; then
            echo "🎯 Running tests matching --grep='${{ github.event.inputs.test_pattern }}'"
            npx playwright test --grep "${{ github.event.inputs.test_pattern }}"
          else
            echo "🎯 Running full Playwright suite"
            npx playwright test
          fi
        env:
          # ─────────────── secrets ───────────────
          SEED_PHRASE: ${{ secrets.SEED_PHRASE }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          WALLET_PASSWORD: ${{ secrets.WALLET_PASSWORD }}
          MY_ADDRESS: ${{ secrets.MY_ADDRESS }}
          # ─────────────── public variables ───────────────
          SEPOLIA_RPC_URL:              ${{ vars.SEPOLIA_RPC_URL }}
          NEURA_TESTNET_RPC_URL:        ${{ vars.NEURA_TESTNET_RPC_URL }}
          SEPOLIA_BRIDGE_PROXY_ADDRESS: ${{ vars.SEPOLIA_BRIDGE_PROXY_ADDRESS }}
          NEURA_BRIDGE_PROXY_ADDRESS:   ${{ vars.NEURA_BRIDGE_PROXY_ADDRESS }}
          ANKR_TOKEN_ADDRESS:           ${{ vars.ANKR_TOKEN_ADDRESS }}
          NEURA_TESTNET_URL:            ${{ vars.NEURA_TESTNET_URL }}
          SUBGRAPH_URL:                 ${{ vars.SUBGRAPH_URL }}

      # ────────────────────────── artifacts / traces ────────────────────────────
      - name: Upload Playwright report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 14

      - name: Upload traces on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: test-results/**/trace.zip
          retention-days: 14