name: Neura E2E Automation

on:
  # ── every 30 minutes ──
  schedule:
    - cron: '*/30 * * * *'
  # ── on any push to main ──
  push:
    branches: ['main']
  # ── on any PR targeting main ──
  pull_request:
    branches: ['main']
  # ── manual trigger with optional inputs ──
  workflow_dispatch:
    inputs:
      spec_file:
        description: 'Path to one spec file (e.g. tests/bridge-ui.spec.js)'
        required: false
        default: ''
      test_pattern:
        description: 'Playwright --grep pattern (test title regex)'
        required: false
        default: ''

jobs:
  e2e:
    name: Neura E2E Automation tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    concurrency:
      group: e2e-${{ github.ref }}-${{ github.event_name == 'schedule' && 'cron' || 'ci' }}
      cancel-in-progress: true

    env:
      SEED_PHRASE:                  ${{ secrets.SEED_PHRASE }}
      PRIVATE_KEY:                  ${{ secrets.PRIVATE_KEY }}
      WALLET_PASSWORD:              ${{ secrets.WALLET_PASSWORD }}
      MY_ADDRESS:                   ${{ secrets.MY_ADDRESS }}
      SEPOLIA_RPC_URL:              ${{ vars.SEPOLIA_RPC_URL }}
      NEURA_TESTNET_RPC_URL:        ${{ vars.NEURA_TESTNET_RPC_URL }}
      SEPOLIA_BRIDGE_PROXY_ADDRESS: ${{ vars.SEPOLIA_BRIDGE_PROXY_ADDRESS }}
      NEURA_BRIDGE_PROXY_ADDRESS:   ${{ vars.NEURA_BRIDGE_PROXY_ADDRESS }}
      ANKR_TOKEN_ADDRESS:           ${{ vars.ANKR_TOKEN_ADDRESS }}
      NEURA_TESTNET_URL:            ${{ vars.NEURA_TESTNET_URL }}
      SUBGRAPH_URL:                 ${{ vars.SUBGRAPH_URL }}
      HEADLESS:                     ${{ vars.HEADLESS }}
      BROWSER_CHANNEL:              ${{ vars.BROWSER_CHANNEL }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm

      - name: Install dependencies (Chromium only)
        run: |
          npm ci
          npx playwright install --with-deps chromium

      - name: Run bridge-flows.spec.js (schedule, push to main, PR to main)
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' npx playwright test --headed tests/bridge-flows.spec.js

      - name: Run single spec file (manual dispatch + spec_file)
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.spec_file != '' }}
        run: xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' test --headed ${{ github.event.inputs.spec_file }}

      - name: Run grep pattern only (manual dispatch + test_pattern)
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.spec_file == '' && github.event.inputs.test_pattern != '' }}
        run: xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' npx playwright test --headed --grep "${{ github.event.inputs.test_pattern }}"

      - name: Run full suite (manual dispatch default)
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.spec_file == '' && github.event.inputs.test_pattern == '' }}
        run: xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' npx playwright test --headed

      - name: Upload Playwright report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 14

      - name: Upload traces on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: test-results/**/trace.zip
          retention-days: 14
